kind: pipeline
name: default
platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: maven:3-eclipse-temurin-17
    commands:
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - mvn test -B
  - name: code-analysis
image: aosapps/drone-sonar-plugin
settings:
  sonar_host:
    from_secret: sonar_host
  sonar_token:
    from_secret: sonar_token
